// Single source of truth for brainrot packs (index collection + shop prices).
window.BRAINROT_CATALOG = [
  {
    id: "skibidi",
    name: "Skibidi Toilet",
    displayName: "Starter Pack",
    rarity: "common",
    starter: true,
    price: 10,
    multiplier: 0.1,
    image: "images/skibidi.png",
  },
  {
    id: "chipi",
    name: "Chipi Chipi Chapa Chapa",
    rarity: "rare",
    price: 25,
    multiplier: 0.2,
    image: "images/chipi.gif",
  },
  {
    id: "fanum",
    name: "Fanum Tax",
    rarity: "rare",
    price: 35,
    multiplier: 0.25,
    image: "images/fanum.png",
  },
  {
    id: "sigma",
    name: "Sigma Grindset",
    rarity: "epic",
    price: 50,
    multiplier: 0.4,
    image: "images/sigma.png",
  },
  {
    id: "gyatt",
    name: "GYATT Mode",
    rarity: "epic",
    price: 65,
    multiplier: 0.45,
    image: "images/gyatt.png",
  },
  {
    id: "ohio",
    name: "Only in Ohio",
    rarity: "legendary",
    price: 80,
    multiplier: 0.7,
    image: "images/ohio.png",
  },
  {
    id: "rizzler",
    name: "The Rizzler",
    rarity: "legendary",
    price: 100,
    multiplier: 0.8,
    image: "images/rizzler.png",
  },
  {
    id: "tung-tung",
    name: "Tung Tung Tung Sahur",
    rarity: "mythic",
    price: 125,
    multiplier: 0.5,
    image: "images/TripleT.jpeg",
  },
];
